config/routes.rb
Rails.application.routes.draw do
  resources :users do
    resources :portfolios
  end

  post '/users/new', to: 'users#create'

  resources :portfolios do
    resources :projects, only: [:index, :show, :new, :edit, :update, :destroy]
  end

  resources :projects

  post '/users/:id/portfolios/new', to: 'portfolios#create'
  post '/portfolios/:id/projects/new', to: 'projects#create'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  root 'pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
  belongs_to :user
  has_many :projects
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :portfolio
end

app/models/user.rb
class User < ApplicationRecord
  has_many :portfolios
  has_many :projects, through: :portfolios

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @greeting = "Welcome to the Portfolio Mania Home Page!"
  end
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  before_action :find_user, only: [:index, :show, :edit, :destroy]
  before_action :find_portfolio, only: [:show, :edit, :update, :destroy]

  def index
    @portfolios = @user.portfolios
  end

  def show
  end

  def new
    @portfolio = Portfolio.new
    @user = User.find(params[:user_id])
  end

  def create
    portfolio = Portfolio.new(portfolio_params)

    if portfolio.save!
      redirect_to user_portfolio_path(portfolio.user, portfolio)
    else
      render :new
    end
  end
  
  def edit
  end

  def update
    if @portfolio.update(portfolio_params)
      redirect_to user_portfolio_path(@portfolio.user, @portfolio)
    else
      render :edit
    end
  end

  def destroy
    @portfolio.destroy
    redirect_to user_path @user
  end

  private

  def find_portfolio
    @portfolio = Portfolio.find(params[:id])
  end

  def find_user
    @user = User.find(params[:user_id])
  end

  def portfolio_params
    params.require(:portfolio).permit(:name, :type, :template, :user_id)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :find_project, only: [:show, :edit, :update, :destroy]
  before_action :find_portfolio, only: [:index, :new]

  def index
    @projects = @portfolio.projects
  end

  def show
  end

  def new
    @project = Project.new(portfolio_id: params[:portfolio_id])
  end

  def create
    project = Project.new(project_params)

    if project.save
      redirect_to portfolio_project_path(project.portfolio, project)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @project.update(project_params)
      redirect_to project_path @project
    else
      render :edit
    end
  end

  def destroy
    portfolio = @project.portfolio
    @project.destroy

    redirect_to user_portfolio_path(current_user, portfolio)
  end

  private

  def find_project
    @project = Project.find(params[:id])
  end

  def find_portfolio
    @portfolio = Portfolio.find(params[:portfolio_id]) 
  end

  def project_params
    params.require(:project).permit(:title, :caption, :description, :thumbnail_url, :portfolio_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    user = User.find_by(username: params[:user][:username])
    
    if user && user.authenticate(params[:user][:password])
      session[:user_id] = user.id
      redirect_to user_path(user)
    else
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
  end

  def show
  end

  def new
    @user = User.new
  end

  def create
    user = User.new(user_params)

    if user.save
      session[:user_id] = user.id
      redirect_to user_path user
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to user_path @user
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to root_path
  end

  private

  def find_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :username, :email, :phone_number, :address_line_1, :address_line_2, :zipcode, :state, :country, :password, :password_confirmation, :avatar_url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Portfolios</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload", media: 'all' %>
    <%= stylesheet_link_tag "portfolio", "data-turbo-track": "reload", media: 'all' %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="container text-center ">
    <h3><%= @greeting %></h3>
</div>

app/views/portfolios/_form.html.erb
<div class="container mt-4">
  <div class="portfolio-form-wrapper">
    <h2 class="mb-4"><%= f.object.new_record? ? 'Create Portfolio' : 'Edit Portfolio' %></h2>

    <div class="form-group">
      <%= f.label :name, 'Portfolio Name', class: 'form-label' %>
      <%= f.text_field :name, class: 'form-control', placeholder: 'Enter portfolio name' %>
    </div>

    <div class="form-group">
      <%= f.label :template, 'Choose a Template', class: 'form-label' %>
      <%= f.select :template, options_for_select([['Template 1', 'template_1'], ['Template 2', 'template_2'], ['Template 3', 'template_3']], f.object.template), { class: 'form-control' } %>
    </div>

    <%= f.hidden_field :user_id, value: @user.id %>

    <div class="form-group">
      <%= f.submit f.object.new_record? ? 'Create Portfolio' : 'Update Portfolio', class: 'btn btn-primary' %>
    </div>
  </div>
</div>

app/views/portfolios/edit.html.erb
<%= form_with model: @portfolio, local: true do |f| %>
  <%= render 'form', f: f %>
<% end %>

app/views/portfolios/index.html.erb
<div class="portfolios-wrapper">
    <h2>Portfolios</h2>
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>#</th>
                <th>Portfolio Name</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            <% @portfolios.each.with_index(1) do |portfolio, i| %>
                <tr>
                    <td><%= i %></td>
                    <td><%= link_to portfolio.name, user_portfolio_path(portfolio.user, portfolio) %></td>
                    <td class="d-flex p-2">
                        <%= link_to 'Edit', edit_user_portfolio_path(portfolio.user, portfolio), class: 'btn btn-warning btn-sm' %>
                        <%= button_to 'Delete', portfolio_path(portfolio), method: :delete, data: { confirm: 'Are you sure you want to delete this portfolio?' }, class: 'btn btn-danger btn-sm' %>
                    </td>
                </tr>
            <% end %>
        </tbody>
    </table>
</div>

app/views/portfolios/new.html.erb
<%= form_with model: @portfolio, local: true do |f| %>
  <%= render 'form', f: f %>
<% end %>

app/views/portfolios/show.html.erb
<div class="portfolio-show-wrapper container">
    <div class="text-center mb-4">
        <h1><%= @portfolio.name %></h1>
        <%= link_to "Add Project", new_portfolio_project_path(@portfolio), class: 'btn btn-primary' %>
    </div>

    <div class="row">
        <% @portfolio.projects.each do |project| %>
            <div class="col-md-4 mb-4">
                <div class="card h-100 shadow-sm text-center">
                    <%= image_tag project.thumbnail_url, class: 'card-img-top img-fluid', alt: project.title %>
                    <div class="card-body">
                        <h5 class="card-title"><%= project.title %></h5>
                        <p class="card-text"><%= project.caption %></p>
                        <div class="text-center">
                            <%= link_to "View Project", portfolio_project_path(@portfolio, project), class: 'btn btn-info' %>
                        </div>
                    </div>
                </div>
            </div>
        <% end %>
    </div>
</div>

app/views/projects/_form.html.erb
<div class="portfolio-projects-wrapper d-flex justify-content-center">
    <div class="col-md-6">
        <h2 class="text-center mb-4"><%= f.object.new_record? ? "Create a new Project" : "Edit Project" %></h2>
        <%= f.label :title, class: 'form-label' %>
        <%= f.text_field :title, class: 'form-control', placeholder: 'Project Title' %>

        <div class="form-group">
            <%= f.label :caption, class: 'form-label' %>
            <%= f.text_field :caption, class: 'form-control', placeholder: 'Project Caption' %>
        </div>

        <div class="form-group">
            <%= f.label :description, class: 'form-label' %>
            <%= f.text_area :description, class: 'form-control', placeholder: 'Project Description', rows: 4 %>
        </div>

        <div class="form-group">
            <%= f.label :thumbnail_url, class: 'form-label' %>
            <%= f.text_field :thumbnail_url, class: 'form-control', placeholder: 'Thumbnail URL' %>
        </div>

        <%= f.hidden_field :portfolio_id, value: @project.portfolio_id %>

        <div class="text-center">
            <%= f.submit f.object.new_record? ? "Create Project" : "Update Project", class: 'btn btn-primary' %>
        </div>
    </div>
</div>

app/views/projects/edit.html.erb
<%= form_for @project do |f| %>
    <%= render 'form', f: f %>
<% end %>

app/views/projects/new.html.erb
<%= form_for @project do |f| %>
    <%= render 'form', f: f %>
<% end %>

app/views/projects/show.html.erb
<div class="portfolio-project-wrapper d-flex justify-content-center">
    <div class="col-md-8 col-lg-6">
        <div class="card shadow-sm mb-4">
            <div class="card-header">
                <h3 class="card-title"><%= @project.title %></h3>
                <div class="text-muted"><i><%= @project.caption %></i></div>
            </div>
            <div class="card-body text-center">
                <div class="mb-3">
                    <%= image_tag @project.thumbnail_url, class: 'img-fluid rounded', alt: @project.title %>
                </div>
                <h5>Description</h5>
                <p><%= @project.description %></p>
            </div>
            <div class="card-footer text-muted">
                <small>Part of Portfolio ID: <%= @project.portfolio_id %></small>
            </div>
        </div>

        <div class="text-center">
            <%= link_to "Edit Project", edit_portfolio_project_path(@project.portfolio, @project), class: 'btn btn-warning' %>
            <%= link_to "Back to Portfolio", user_portfolio_path(@project.portfolio.user, @project.portfolio_id), class: 'btn btn-secondary ml-2' %>
            <%= button_to 'Remove Project', portfolio_project_path(@project.portfolio_id, @project), class: 'btn btn-danger', method: :delete %>
        </div>
    </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
        <%= link_to "Home", root_path, class: 'navbar-brand'%>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <% if session[:user_id] %>
                    <li class="nav-item">
                        <%= link_to 'Portfolios', user_portfolios_path(session[:user_id]), class: 'nav-link active'%>
                    </li>
                    <li class="nav-item">
                        <%= link_to 'New Portfolio', new_user_portfolio_path(session[:user_id]), class: 'nav-link active'%>
                    </li>
                    <li class="nav-item">
                        <%= button_to 'Logout', logout_path, class: 'nav-link active', method: :delete %>
                    </li>

                <% else %>
                    <li class="nav-item">
                        <%= link_to 'Login', login_path, class: 'nav-link active'%>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link">/</a>
                    </li>
                    <li class="nav-item">
                        <%= link_to 'Sign Up', new_user_path, class: 'nav-link active'%>
                    </li>
                <% end %>
            </ul>
            <form class="d-flex" role="search">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
        </div>
    </div>
</nav>

app/views/users/_form.html.erb
<div class="container">
  <%= form_for :user, class: 'form' do |f| %>
    <div>
      <h1 class="header">Sign Up</h1>
    </div>

    <div class="form-group row mb-3">
      <%= f.label :first_name, class: 'col-sm-2 col-form-label' %>
      <div class="col-sm-10">
        <%= f.text_field :first_name, class: 'form-control' %>
      </div>
    </div>

    <div class="form-group row mb-3">
      <%= f.label :last_name, class: 'col-sm-2 col-form-label' %>
      <div class="col-sm-10">
        <%= f.text_field :last_name, class: 'form-control' %>
      </div>
    </div>

    <div class="form-group row mb-3">
      <%= f.label :email, class: 'col-sm-2 col-form-label' %>
      <div class="col-sm-10">
        <%= f.email_field :email, class: 'form-control' %>
      </div>
    </div>

    <div class="form-group row mb-3">
      <%= f.label :phone_number, class: 'col-sm-2 col-form-label' %>
      <div class="col-sm-10">
        <%= f.telephone_field :phone_number, class: 'form-control' %>
      </div>
    </div>

    <div class="form-group row mb-3">
      <%= f.label :username, class: 'col-sm-2 col-form-label' %>
      <div class="col-sm-10">
        <%= f.text_field :username, class: 'form-control' %>
      </div>
    </div>

    <div class="form-group row mb-3">
      <%= f.label :password, "Create a Password", class: 'col-sm-2 col-form-label' %>
      <div class="col-sm-10">
        <%= f.password_field :password, class: 'form-control' %>
      </div>
    </div>

    <div class="form-group row mb-3">
      <%= f.label :password_confirmation, "Confirm Password", class: 'col-sm-2 col-form-label' %>
      <div class="col-sm-10">
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>
    </div>

    <div class="form-group row mb-3">
      <%= f.label :address_line_1, class: 'col-sm-2 col-form-label' %>
      <div class="col-sm-10">
        <%= f.text_field :address_line_1, class: 'form-control' %>
      </div>
    </div>

    <div class="form-group row mb-3">
      <%= f.label :address_line_2, class: 'col-sm-2 col-form-label' %>
      <div class="col-sm-10">
        <%= f.text_field :address_line_2, class: 'form-control' %>
      </div>
    </div>

    <div class="form-group row mb-3">
      <%= f.label :zipcode, class: 'col-sm-2 col-form-label' %>
      <div class="col-sm-10">
        <%= f.text_field :zipcode, class: 'form-control' %>
      </div>
    </div>

    <div class="form-group row mb-3">
      <%= f.label :state, class: 'col-sm-2 col-form-label' %>
      <div class="col-sm-10">
        <%= f.text_field :state, class: 'form-control' %>
      </div>
    </div>

    <div class="form-group row mb-3">
      <%= f.label :country, class: 'col-sm-2 col-form-label' %>
      <div class="col-sm-10">
        <%= f.text_field :country, class: 'form-control' %>
      </div>
    </div>

    <div class="form-group row mb-3">
      <%= f.label :avatar_url, class: 'col-sm-2 col-form-label' %>
      <div class="col-sm-10">
        <%= f.text_field :avatar_url, class: 'form-control' %>
      </div>
    </div>

    <div class="form-group">
      <%= f.submit "Sign Up", class: 'btn btn-outline-success' %>
    </div>
  <% end %>
</div>

app/views/users/edit.html.erb
<%= form_with(model: @user, local: true) do |form| %>
  <%= render 'form', form: form %>
<% end %>

<%= link_to 'Back to Users', users_path, class: 'btn btn-secondary' %>

app/views/users/new.html.erb
<%= form_with(model: @user, local: true) do |form| %>
  <%= render 'form', form: form %>
<% end %>

<%= link_to 'Back to Users', users_path, class: 'btn btn-secondary' %>

app/views/users/show.html.erb
<div>
    <p>Welcome, <%= @user.first_name %> <%= @user.last_name %>!</p>
</div>